const LOGIN_STARTED = 'user/LOGIN_STARTED';
const LOGIN_SUCCESS = 'user/LOGIN_SUCCESS';
const LOGIN_ERROR = 'user/LOGIN_ERROR';
const LOGOUT = 'user/LOGOUT';

export {
    LOGIN_STARTED,
    LOGIN_ERROR,
    LOGIN_SUCCESS,
    LOGOUT
};
