const LOGIN_STARTED = 'user/LOGIN_STARTED';
const LOGIN_SUCCESS = 'user/LOGIN_SUCCESS';
const LOGIN_ERROR = 'user/LOGIN_ERROR';
const LOGOUT = 'user/LOGOUT';
const SHOW_MODAL = 'SHOW_MODAL';
const HIDE_MODAL = 'HIDE_MODAL';
const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER'
const SUCCESS_MESSAGE = 'SUCCESS_MESSAGE'

export {
    LOGIN_STARTED,
    LOGIN_ERROR,
    LOGIN_SUCCESS,
    LOGOUT,
    SHOW_MODAL,
    HIDE_MODAL,
    LOGIN_SUCCESS_USER,
    SUCCESS_MESSAGE
};
