module.exports = {
  'home':                 '/',
  'users':                '/users',
  'admin':                '/admin',
  'register':             '/register',
  'apiv1':                '/apiv1',
  'apiv1_user':           '/apiv1/user',
  'apiv1_delete_user':    '/apiv1/deleteuser',
  'apiv1_article':        '/apiv1/article',
  'apiv1_fav_article':    '/apiv1/favarticle',
  'articles':             '/articles',
  'article':              '/article',
  'design':               '/design',
  'search':               '/search',
};
