const SHOW_FORM = 'SHOW_FORM';
const SUCCESS_MESSAGE = 'SUCCESS_MESSAGE';
const SUCCESS_MESSAGE_EDIT = ' SUCCESS_MESSAGE_EDIT';
const HIDE_ARTCILE_MODAL = 'HIDE_ARTCILE_MODAL';
const GET_ARTICLES = 'GET_ARTICLES';
const ARTICLES_LOADED = 'ARTICLES_LOADED';

export {
    SHOW_FORM,
    SUCCESS_MESSAGE,
    SUCCESS_MESSAGE_EDIT,
    HIDE_ARTCILE_MODAL,
    GET_ARTICLES,
    ARTICLES_LOADED
};
