const SHOW_FORM = 'SHOW_FORM';
const SUCCESS_MESSAGE = 'SUCCESS_MESSAGE';
const SUCCESS_MESSAGE_EDIT = ' SUCCESS_MESSAGE_EDIT';

export {
    SHOW_FORM,
    SUCCESS_MESSAGE,
    SUCCESS_MESSAGE_EDIT
};
